name: Update Lists
permissions: write-all

on:
  push:
    branches:
      - main
  schedule:
    # Run every day
    - cron: "0 8 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: python -m pip install --upgrade pip && pip install -r requirements.txt

    - name: Run Python script and save results
      run: python update.py

    - name: Commit and push files
      uses: EndBug/add-and-commit@v7
      with:
        author_name: "Github Actions" 
        author_email: "actions@github.com"
        message: "Auto update"
        add: "."
        push: "https://github.com/IRConf/Iranian-Half-Price-Traffic-Websites-List.git"
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
